### ISSUE TITLE
error on get friend list

### ISSUE THREAD

**Issue by segator** [jakewaldron/PlexEmail#48]
Checking the app logs I see the next error:

2016-09-05 19:38:05,116 - INFO:getSharedUserEmails: url = https://plex.tv/pms/friends/all
2016-09-05 19:38:05,122 - INFO:Starting new HTTPS connection (1): plex.tv
2016-09-05 19:38:06,374 - INFO:getSharedUserEmails: response = <Response [200]>
2016-09-05 19:38:06,375 - ERROR:Logging an uncaught exception
Traceback (most recent call last):
  File "/app/plexemail/scripts/plexEmail.py", line 1659, in <module>
    sharedEmails = getSharedUserEmails()
  File "/app/plexemail/scripts/plexEmail.py", line 332, in getSharedUserEmails
    logging.info('getSharedUserEmails: response = ' + str(response.text))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 12682: ordinal not in range(128)

**Comment by jakewaldron** [comment]
For now, you should be able to remove line 332 in plexEmail.py and it should work.  I will put in a fix during the next release.

**Comment by jakewaldron** [comment]
I just pushed new changes to the master branch that has a fix for this.  Could you please try it?
