### ISSUE TITLE
Plexemail Started Failing on Cloudinary

### ISSUE THREAD

**Issue by Marcelofs1** [jakewaldron/PlexEmail#83]
Hello 
I was running my Plexemail script flawless after struggling for a couple weeks. Then I moved and switched to AT&T U-Verse (I know but it is the only provider here) and, coincidence or not the script failed. Last time it worked was on June 02nd. I moved on June 3 and since then I am trying to make it work
Looking at the logs, I got this,

2017-06-18 19:04:43,945 - INFO:processImage: Uploading to cloudinary
2017-06-18 19:04:43,946 - INFO:uploadToCloudinary: begin
2017-06-18 19:04:43,946 - INFO:uploadToCloudinary: start upload to cloudinary
2017-06-18 21:14:47,930 - ERROR:Logging an uncaught exception
Traceback (most recent call last):
  File "plexEmail.py", line 1070, in <module>
    imageInfo = processImage(hash, imageInfo['thumb'], 'movie', 0, 0)
  File "plexEmail.py", line 435, in processImage
    cloudinaryURL = uploadToCloudinary(imgLocation)
  File "plexEmail.py", line 493, in uploadToCloudinary
    response = cloudinary.uploader.upload(imgToUpload)
  File "/PlexEmail/scripts/cloudinary/uploader.py", line 16, in upload
    return call_api("upload", params, file = file, **options)
  File "/PlexEmail/scripts/cloudinary/uploader.py", line 210, in call_api
    raise Error("Socket error: %s" % str(e))
Error: Socket error: [Errno 60] Operation timed out

Searching around, I found this post but could not find the specific line mentioned. https://github.com/jakewaldron/PlexEmail/issues/42

I did update the script to the new version 0.9.3 (was 0.9.0) and got the same result. I also tested my access to Cloudinary and everything is ok, including the token, space, bandwidth, limits, etc.
Any guidance? Really appreciate.
Thank you
Marcelo

**Comment by Marcelofs1** [comment]
No idea why but started working back again. My guess is that there were some temporary error on Cloudinary
