### ISSUE TITLE
erro sending mails  my.plexapp.com

### ISSUE THREAD

**Issue by carlosmg2** [jakewaldron/PlexEmail#90]
Today mails didn't go out because of this error:

`2018-01-12 13:03:27,868 - INFO:getSharedUserEmails: begin
2018-01-12 13:03:27,868 - INFO:getSharedUserEmails: url = https://my.plexapp.com/users/sign_in.json
2018-01-12 13:03:28,081 - INFO:Starting new HTTPS connection (1): my.plexapp.com
2018-01-12 13:03:28,581 - ERROR:Logging an uncaught exception
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\PlexEmail-master\scripts\plexEmail.py", line 1683, in <module>
    sharedEmails = getSharedUserEmails()
  File "C:\Program Files (x86)\Plex\PlexEmail-master\scripts\plexEmail.py", line 323, in getSharedUserEmails
    response = requests.post(url, headers=headers)
  File "C:\Python27\lib\requests\api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\requests\api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\requests\sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\requests\adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: hostname 'my.plexapp.com' doesn't match either of 'plex.tv', 'www.plex.tv'`

**Comment by jakewaldron** [comment]
Hey there, looks like things might have changed on the plex side for authentication.  Could you try replacing line 327 in plexEmail.py with this:

url = 'https://plex.tv/users/sign_in.json'

**Comment by carlosmg2** [comment]
Yup. Worked nice. Thanks a lot for the fix

**Comment by Tolagarf** [comment]
Doesn't work for me, now I get this error: 

C:\Python27>python c:\tools\plexemail\scripts\plexemail.py
  File "c:\tools\plexemail\scripts\plexemail.py", line 327
    url = 'https://plex.tv/users/sign_in.json'
                                             ^
IndentationError: unindent does not match any outer indentation level

Edit: I completely reinstalled PlexEmail and manually added in my info again, edited line 327 in plexEmail.py and now it seems to work, at least with a -t. It's possibly my install somehow got corrupted.
